# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translifyapp', '0002_auto_20180506_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTranslationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=65536)),
                ('image', models.BinaryField()),
                ('ext', models.CharField(max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PublicTranslationEntry',
            },
        ),
    ]
